//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestingResults
    {
        public int TestId { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> Answer { get; set; }
        public Nullable<int> TestDuration { get; set; }
        public Nullable<int> TotalQuestions { get; set; }
        public Nullable<int> CorrectAnswers { get; set; }
        public Nullable<int> Grade { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual Students Students { get; set; }
    }
}
